<!DOCTYPE html>
<html lang="en"><head>
<script src="ch13_files/libs/clipboard/clipboard.min.js"></script>
<script src="ch13_files/libs/quarto-html/tabby.min.js"></script>
<script src="ch13_files/libs/quarto-html/popper.min.js"></script>
<script src="ch13_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="ch13_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ch13_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="ch13_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <title>Chapter 13: Fiscal Policy, Deficits, and Debt</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="ch13_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="ch13_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="ch13_files/libs/revealjs/dist/theme/quarto-47ef377ee77cdf85c61adfa0b07e2c12.css">
  <link href="ch13_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="ch13_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="ch13_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="ch13_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title"><p>Chapter 13: Fiscal Policy, Deficits, and Debt</p></h1>
  <p class="subtitle"></p><div class="line-block">ECO 112 Principles of Macroeconomics</div><p></p>

<div class="quarto-title-authors">
</div>

</section>
<section id="todays-roadmap" class="slide level2">
<h2>Today’s Roadmap</h2>
<h3 id="key-concepts">Key Concepts</h3>
<ul>
<li>Discretionary fiscal policy: deliberately changing government spending (G) and taxes (T) to shift aggregate demand</li>
<li>Expansionary fiscal policy (fight a recessionary gap) versus contractionary fiscal policy (fight an inflationary gap)</li>
<li>The G-multiplier versus the T-multiplier, and the balanced-budget multiplier</li>
<li>Automatic (non-discretionary) stabilizers: how the tax and transfer system cushions the economy without new legislation</li>
<li>Progressive, proportional, and regressive tax structures, and why a more progressive system stabilizes more</li>
<li>The actual budget deficit/surplus versus the cyclically adjusted (full-employment) budget</li>
<li>The public debt: how it accumulates, how to measure it, and who holds it</li>
<li>The crowding-out effect, and a preview of monetary policy in Chapters 14-15</li>
</ul>
<!-- IMAGE PLACEHOLDER: U.S. Capitol building or federal budget document, suggesting fiscal policy -->
</section>
<section>
<section id="discretionary-fiscal-policy-and-the-multiplier" class="title-slide slide level1 center">
<h1>Discretionary Fiscal Policy and the Multiplier</h1>

</section>
<section id="connecting-back-the-adas-model-chapter-12" class="slide level2">
<h2>Connecting Back: The AD/AS Model (Chapter 12)</h2>
<div style="font-size: 1.2em;">
<p>Chapter 12 built the <strong>aggregate demand and aggregate supply (AD/AS) model</strong>: aggregate demand slopes down, short-run aggregate supply slopes up, and equilibrium output and the price level are set where they cross.</p>
<ul>
<li>Aggregate demand (AD) can shift right or left, moving equilibrium GDP and the price level.</li>
<li>This chapter treats AD/AS as an <em>established tool</em> and asks a policy question: can the government deliberately shift AD on purpose?</li>
</ul>
<p><em>Fiscal policy is exactly that: using government spending and taxes as levers to shift AD.</em></p>
</div>
</section>
<section id="connecting-back-the-multiplier-chapters-10-11" class="slide level2">
<h2>Connecting Back: The Multiplier (Chapters 10-11)</h2>
<div style="font-size: 1.2em;">
<p>Chapters 10 and 11 showed that a change in spending gets <em>re-spent</em> through the economy, so it produces a <em>larger</em> final change in equilibrium GDP.</p>
<ul>
<li>Spending multiplier: <span class="math inline">\(1/\text{MPS}\)</span></li>
<li>A change in government purchases (<span class="math inline">\(\Delta G\)</span>) shifts equilibrium GDP by <span class="math inline">\(\Delta G \times \text{multiplier}\)</span>.</li>
<li>A change in taxes (<span class="math inline">\(\Delta T\)</span>) shifts equilibrium GDP by <span class="math inline">\(\Delta T \times \text{MPC} \times \text{multiplier}\)</span>, smaller than an equal-sized change in G, since part of a tax change is absorbed by saving rather than spending.</li>
</ul>
<p><em>This chapter puts these tools to work as deliberate policy.</em></p>
</div>
</section>
<section id="connecting-back-expenditure-gaps-and-the-business-cycle-chapters-9-11" class="slide level2">
<h2>Connecting Back: Expenditure Gaps and the Business Cycle (Chapters 9-11)</h2>
<div style="font-size: 1.2em;">
<p>Chapter 9 described the business cycle and the difference between <em>demand-pull</em> inflation (too much spending chasing output) and <em>cost-push</em> inflation (rising input costs). Chapter 11 introduced <strong>recessionary</strong> and <strong>inflationary expenditure gaps</strong>.</p>
<ul>
<li>A recessionary gap: equilibrium GDP sits <em>below</em> full-employment (potential) GDP.</li>
<li>An inflationary gap: spending is pulling the economy <em>above</em> potential GDP, risking demand-pull inflation.</li>
</ul>
<p><em>Fiscal policy is the deliberate attempt to close these gaps by shifting AD.</em></p>
</div>
</section>
<section id="what-is-discretionary-fiscal-policy" class="slide level2">
<h2>What Is Discretionary Fiscal Policy?</h2>
<div style="font-size: 1.2em;">
<p><strong>Discretionary fiscal policy</strong> is the <em>deliberate</em>, legislated use of government spending and taxes to stabilize the economy. It requires new legislation, Congress and the President must actively decide to change G or T.</p>
<ul>
<li>This is distinct from <em>automatic stabilizers</em> (covered next section), which work without any new law.</li>
<li>In the U.S., policy recommendations often come from bodies like the <strong>Council of Economic Advisers</strong>, which advises the President on macroeconomic conditions.</li>
</ul>
<p><em>Discretionary fiscal policy is a choice. Automatic stabilizers are not.</em></p>
</div>
</section>
<section id="who-makes-fiscal-policy" class="slide level2">
<h2>Who Makes Fiscal Policy?</h2>
<div style="font-size: 1.2em;">
<p>Fiscal policy in the U.S. is set through the political process, not by a single independent agency.</p>
<ul>
<li><strong>Congress</strong> must pass spending bills and tax legislation.</li>
<li>The <strong>President</strong> proposes budgets, signs or vetoes legislation, and receives advice from the Council of Economic Advisers.</li>
<li>Because it requires legislation, discretionary fiscal policy can be slow to enact compared to other policy tools, an idea we return to shortly.</li>
</ul>
</div>
</section>
<section id="expansionary-fiscal-policy" class="slide level2">
<h2>Expansionary Fiscal Policy</h2>
<div style="font-size: 1.2em;">
<p><strong>Expansionary fiscal policy</strong> is used to close a <em>recessionary</em> gap, that is, to fight a recession.</p>
<ul>
<li><em>Increase</em> government spending (G), <em>or</em></li>
<li><em>Decrease</em> taxes (T), <em>or</em></li>
<li>Some combination of both</li>
</ul>
<p>Each of these shifts AD to the <em>right</em>, raising equilibrium GDP (and, in AD/AS terms, moving output toward potential GDP).</p>
</div>
</section>
<section id="contractionary-fiscal-policy" class="slide level2">
<h2>Contractionary Fiscal Policy</h2>
<div style="font-size: 1.2em;">
<p><strong>Contractionary fiscal policy</strong> is used to close an <em>inflationary</em> gap, that is, to fight demand-pull inflation.</p>
<ul>
<li><em>Decrease</em> government spending (G), <em>or</em></li>
<li><em>Increase</em> taxes (T), <em>or</em></li>
<li>Some combination of both</li>
</ul>
<p>Each of these shifts AD to the <em>left</em>, lowering equilibrium GDP (and easing upward pressure on the price level).</p>
</div>
</section>
<section id="the-g-multiplier-vs.-the-t-multiplier" class="slide level2">
<h2>The G-Multiplier vs.&nbsp;the T-Multiplier</h2>
<div style="font-size: 1.2em;">
<p><span class="math display">\[
\Delta \text{GDP} = \Delta G \times \text{multiplier}, \qquad \text{multiplier} = \frac{1}{\text{MPS}}
\]</span></p>
<p><span class="math display">\[
\Delta \text{GDP} = \Delta T \times \text{MPC} \times \text{multiplier}
\]</span></p>
<p>A dollar of spending has a <em>bigger</em> effect on equilibrium GDP than a dollar of tax change, because a tax change is only partly spent (some is saved), while a spending change is spent in full, immediately.</p>
</div>
</section>
<section id="example-closing-a-recessionary-gap" class="slide level2">
<h2>Example: Closing a Recessionary Gap</h2>
<div style="font-size: 1.2em;">
<p>An economy has a recessionary gap: equilibrium GDP needs to rise by $300 billion (illustrative) to reach full-employment GDP. The MPC is <span class="math inline">\(0.75\)</span>.</p>
<ol type="1">
<li>Compute the spending multiplier and the tax multiplier.</li>
<li>If policymakers use <em>only</em> a change in G, how large a change is needed?</li>
<li>If policymakers use <em>only</em> a change in T, how large a change is needed?</li>
<li>Find one combination of a <em>simultaneous</em> change in G and T that closes the gap.</li>
</ol>
</div>
</section>
<section id="solution-closing-a-recessionary-gap" class="slide level2">
<h2>Solution: Closing a Recessionary Gap</h2>
<div style="font-size: 1.15em;">
<ol type="1">
<li>Multiplier <span class="math inline">\(= 1/\text{MPS} = 1/0.25 = 4\)</span>. Tax multiplier <span class="math inline">\(= \text{MPC} \times \text{multiplier} = 0.75 \times 4 = 3\)</span>.</li>
</ol>
</div>
<div class="fragment">
<div style="font-size: 1.15em;">
<ol start="2" type="1">
<li>G alone: <span class="math inline">\(\Delta G = 300 / 4 = 75\)</span>. Increase G by $75 billion.</li>
</ol>
</div>
</div>
<div class="fragment">
<div style="font-size: 1.15em;">
<ol start="3" type="1">
<li>T alone: <span class="math inline">\(\Delta T = 300 / 3 = 100\)</span>. Decrease T by $100 billion.</li>
</ol>
</div>
</div>
<div class="fragment">
<div style="font-size: 1.15em;">
<ol start="4" type="1">
<li>Combination: increase G by $45 billion <em>and</em> decrease T by $40 billion. Check: <span class="math inline">\(45 \times 4 = 180\)</span>, plus <span class="math inline">\(40 \times 3 = 120\)</span>, total <span class="math inline">\(= 300\)</span>. <em>Exactly closes the gap.</em></li>
</ol>
</div>
</div>
</section>
<section id="harder-problem-closing-an-inflationary-gap" class="slide level2">
<h2>Harder Problem: Closing an Inflationary Gap</h2>
<div style="font-size: 1.2em;">
<p>A different economy has an <em>inflationary</em> gap: equilibrium GDP needs to <em>fall</em> by $240 billion to reach full-employment GDP. The MPC here is <span class="math inline">\(0.6\)</span>.</p>
<ol type="1">
<li>Compute the spending multiplier and the tax multiplier for this economy.</li>
<li>If policymakers use <em>only</em> a change in G, how large a change is needed, and in which direction?</li>
<li>If policymakers use <em>only</em> a change in T, how large a change is needed, and in which direction?</li>
<li>Find one combination of a simultaneous change in G and T that closes the gap.</li>
</ol>
<p>Work through this with a partner or in a small group before checking the next slide.</p>
</div>
</section>
<section id="review-closing-an-inflationary-gap" class="slide level2">
<h2>Review: Closing an Inflationary Gap</h2>
<div style="font-size: 1.1em;">
<ol type="1">
<li>Multiplier <span class="math inline">\(= 1/0.4 = 2.5\)</span>. Tax multiplier <span class="math inline">\(= 0.6 \times 2.5 = 1.5\)</span>.</li>
</ol>
</div>
<div class="fragment">
<div style="font-size: 1.1em;">
<ol start="2" type="1">
<li>G alone: <span class="math inline">\(\Delta G = 240 / 2.5 = 96\)</span>. <em>Decrease</em> G by $96 billion.</li>
</ol>
</div>
</div>
<div class="fragment">
<div style="font-size: 1.1em;">
<ol start="3" type="1">
<li>T alone: <span class="math inline">\(\Delta T = 240 / 1.5 = 160\)</span>. <em>Increase</em> T by $160 billion.</li>
</ol>
</div>
</div>
<div class="fragment">
<div style="font-size: 1.1em;">
<ol start="4" type="1">
<li>Combination: decrease G by $60 billion <em>and</em> increase T by $60 billion. Check: <span class="math inline">\(60 \times 2.5 = 150\)</span>, plus <span class="math inline">\(60 \times 1.5 = 90\)</span>, total <span class="math inline">\(= 240\)</span>. <em>Exactly closes the gap.</em></li>
</ol>
</div>
</div>
</section>
<section id="the-balanced-budget-multiplier" class="slide level2">
<h2>The Balanced-Budget Multiplier</h2>
<div style="font-size: 1.2em;">
<p>What if G and T rise by the <em>same</em> dollar amount, so the budget balance doesn’t change? You might guess the effect on GDP is zero. It is not.</p>
<ul>
<li>The spending multiplier (<span class="math inline">\(1/\text{MPS}\)</span>) is always <em>larger</em> than the tax multiplier (<span class="math inline">\(\text{MPC}/\text{MPS}\)</span>), because all of a spending increase is spent, while only part of after-tax income is spent.</li>
<li>The <strong>balanced-budget multiplier</strong> shows that an equal increase in G and T still <em>raises</em> equilibrium GDP, by exactly the amount of the increase.</li>
</ul>
<p><span class="math display">\[
\text{multiplier} - \text{MPC} \times \text{multiplier} = (1 - \text{MPC}) \times \frac{1}{\text{MPS}} = \frac{\text{MPS}}{\text{MPS}} = 1
\]</span></p>
</div>
</section>
<section id="example-the-balanced-budget-multiplier" class="slide level2">
<h2>Example: The Balanced-Budget Multiplier</h2>
<div style="font-size: 1.2em;">
<p>An economy has MPC <span class="math inline">\(= 0.75\)</span> (multiplier <span class="math inline">\(= 4\)</span>, tax multiplier <span class="math inline">\(= 3\)</span>, as before, but use fresh numbers here). Congress raises both G and T by $60 billion each, keeping the budget balance unchanged.</p>
<ol type="1">
<li>What is the GDP effect of the $60 billion increase in G alone?</li>
<li>What is the GDP effect of the $60 billion increase in T alone?</li>
<li>What is the <em>net</em> effect on equilibrium GDP?</li>
</ol>
</div>
</section>
<section id="solution-the-balanced-budget-multiplier" class="slide level2">
<h2>Solution: The Balanced-Budget Multiplier</h2>
<div style="font-size: 1.2em;">
<ol type="1">
<li>G effect: <span class="math inline">\(60 \times 4 = 240\)</span> (GDP rises by 240).</li>
</ol>
</div>
<div class="fragment">
<div style="font-size: 1.2em;">
<ol start="2" type="1">
<li>T effect: <span class="math inline">\(60 \times 3 = 180\)</span> (GDP falls by 180).</li>
</ol>
</div>
</div>
<div class="fragment">
<div style="font-size: 1.2em;">
<ol start="3" type="1">
<li>Net effect: <span class="math inline">\(240 - 180 = 60\)</span>. Equilibrium GDP rises by exactly $60 billion, the <em>same</em> as the dollar increase in G and T. <em>This confirms the balanced-budget multiplier equals 1.</em></li>
</ol>
</div>
</div>
</section>
<section id="lags-in-fiscal-policy" class="slide level2">
<h2>Lags in Fiscal Policy</h2>
<div style="font-size: 1.2em;">
<p>Discretionary fiscal policy sounds precise on paper, but in practice it is slowed by several <em>lags</em>:</p>
<ul>
<li><strong>Recognition lag</strong>: time to realize a recession or inflationary episode is actually happening.</li>
<li><strong>Administrative lag</strong>: time for Congress to debate, negotiate, and pass legislation.</li>
<li><strong>Operational lag</strong>: time for approved spending or tax changes to actually affect the economy.</li>
</ul>
<p><em>By the time a discretionary fiscal policy takes effect, the economy may already be changing on its own. This is one reason automatic stabilizers, covered next, are valuable.</em></p>
</div>
</section></section>
<section>
<section id="automatic-stabilizers" class="title-slide slide level1 center">
<h1>Automatic Stabilizers</h1>

</section>
<section id="automatic-non-discretionary-stabilizers" class="slide level2">
<h2>Automatic (Non-Discretionary) Stabilizers</h2>
<div style="font-size: 1.2em;">
<p><strong>Automatic stabilizers</strong> are features built into the tax and transfer system that stabilize the economy <em>without</em> any new legislation.</p>
<ul>
<li>As GDP <em>rises</em> (an expansion), tax revenues automatically rise (with a progressive tax system) and transfer payments (like unemployment benefits) automatically fall. This automatically <em>restrains</em> an overheating expansion.</li>
<li>As GDP <em>falls</em> (a recession), tax revenues automatically fall and transfer payments automatically rise. This automatically <em>cushions</em> the downturn.</li>
</ul>
<p><em>No one has to pass a law. The system responds on its own, immediately.</em></p>
</div>
</section>
<section id="three-tax-structures-progressive-proportional-regressive" class="slide level2">
<h2>Three Tax Structures: Progressive, Proportional, Regressive</h2>
<div style="font-size: 1.2em;">
<p>The strength of automatic stabilization depends on the <em>shape</em> of the tax system:</p>
<ul>
<li><strong>Progressive tax</strong>: the average tax rate <em>rises</em> as income rises.</li>
<li><strong>Proportional tax</strong>: the average tax rate stays <em>constant</em> as income rises (a flat tax).</li>
<li><strong>Regressive tax</strong>: the average tax rate <em>falls</em> as income rises.</li>
</ul>
<p><em>A more progressive tax system provides more automatic stabilization, since tax revenue (and therefore after-tax income) swings by more automatically as GDP moves.</em></p>
</div>
</section>
<section id="example-progressive-vs.-proportional-stabilization" class="slide level2">
<h2>Example: Progressive vs.&nbsp;Proportional Stabilization</h2>
<div style="font-size: 1.2em;">
<p>An economy’s GDP falls from $1{,}000 billion to $800 billion (illustrative). Compare two hypothetical tax systems:</p>
<ul>
<li><strong>Proportional system</strong>: a flat <span class="math inline">\(20\%\)</span> average tax rate at every GDP level.</li>
<li><strong>Progressive system</strong>: average tax rate is <span class="math inline">\(25\%\)</span> at GDP <span class="math inline">\(= 1{,}000\)</span>, falling to <span class="math inline">\(15\%\)</span> at GDP <span class="math inline">\(= 800\)</span>.</li>
</ul>
<ol type="1">
<li>Compute tax revenue at both GDP levels under each system.</li>
<li>Compute after-tax (disposable) income at both GDP levels under each system.</li>
<li>Which system cushions the fall in disposable income more?</li>
</ol>
</div>
</section>
<section id="solution-progressive-vs.-proportional-stabilization" class="slide level2">
<h2>Solution: Progressive vs.&nbsp;Proportional Stabilization</h2>
<div class="columns">
<div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>GDP 1,000</th>
<th>GDP 800</th>
<th>Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Proportional revenue</td>
<td>200</td>
<td>160</td>
<td>-40</td>
</tr>
<tr class="even">
<td>Progressive revenue</td>
<td>250</td>
<td>120</td>
<td>-130</td>
</tr>
<tr class="odd">
<td>Proportional disp. income</td>
<td>800</td>
<td>640</td>
<td>-160</td>
</tr>
<tr class="even">
<td>Progressive disp. income</td>
<td>750</td>
<td>680</td>
<td>-70</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:50%;">
<div style="font-size: 1.1em;">
<p>Tax revenue <em>falls by more</em> under the progressive system ($130 vs.&nbsp;$40), which sounds bad for government revenue, but it means <em>disposable income falls by much less</em> ($70 vs.&nbsp;$160).</p>
<p><em>The progressive system automatically absorbs more of the GDP shock through taxes, leaving households’ after-tax income, and therefore their spending, more stable.</em></p>
</div>
</div></div>
</section>
<section id="automatic-stabilizers-in-the-real-world" class="slide level2">
<h2>Automatic Stabilizers in the Real World</h2>
<div style="font-size: 1.2em;">
<ul>
<li>The <strong>progressive federal income tax</strong>: as incomes fall in a downturn, households move into lower brackets, so tax bills fall automatically.</li>
<li><strong>Unemployment insurance</strong>: benefits rise automatically as more people lose jobs, without new legislation.</li>
<li>Means-tested transfer programs (food assistance, for example) automatically expand as more households qualify during a downturn.</li>
</ul>
<p><em>Automatic stabilizers act instantly, no recognition lag, no administrative lag, no operational lag. Their downside is that they are typically too small, on their own, to fully close a large expenditure gap.</em></p>
</div>
</section>
<section id="discussion-automatic-vs.-discretionary-policy" class="slide level2">
<h2>Discussion: Automatic vs.&nbsp;Discretionary Policy</h2>
<div style="font-size: 1.2em;">
<ol type="1">
<li>Why might policymakers still want discretionary fiscal policy, even with automatic stabilizers already in place?</li>
<li>During a very deep recession, would you expect automatic stabilizers alone to be enough to close the entire recessionary gap? Why or why not?</li>
</ol>
<p><em>Automatic stabilizers cushion the swings. Discretionary fiscal policy is the tool for a deliberate, larger push.</em></p>
</div>
</section></section>
<section>
<section id="actual-vs.-cyclically-adjusted-budget" class="title-slide slide level1 center">
<h1>Actual vs.&nbsp;Cyclically Adjusted Budget</h1>

</section>
<section id="the-actual-budget-deficit-or-surplus" class="slide level2">
<h2>The Actual Budget Deficit or Surplus</h2>
<div style="font-size: 1.2em;">
<p>The <strong>actual budget deficit or surplus</strong> is simply what literally happened in a given year: actual government spending minus actual government revenue.</p>
<ul>
<li>A budget <em>deficit</em> occurs when spending exceeds revenue in that year.</li>
<li>A budget <em>surplus</em> occurs when revenue exceeds spending.</li>
</ul>
<p><em>Problem: because of automatic stabilizers, the actual budget can show a large deficit purely because the economy is in a recession, not because policymakers deliberately chose an expansionary stance.</em></p>
</div>
</section>
<section id="the-cyclically-adjusted-budget" class="slide level2">
<h2>The Cyclically Adjusted Budget</h2>
<div style="font-size: 1.2em;">
<p>The <strong>cyclically adjusted budget</strong> (also called the <strong>full-employment budget</strong>) asks a different question: what would the deficit or surplus be if the economy were operating exactly at full-employment (potential) GDP, using the <em>current</em> tax and spending laws?</p>
<ul>
<li>This strips out the effect of <em>where the economy happens to be</em> in the business cycle.</li>
<li>It reveals whether fiscal <em>policy itself</em> is expansionary, neutral, or contractionary, independent of automatic stabilizers.</li>
</ul>
<p><em>The actual budget tells you what happened. The cyclically adjusted budget tells you what policymakers actually chose.</em></p>
</div>
</section>
<section id="example-actual-vs.-cyclically-adjusted-budget" class="slide level2">
<h2>Example: Actual vs.&nbsp;Cyclically Adjusted Budget</h2>
<div style="font-size: 1.2em;">
<p>An economy’s potential GDP is $1{,}000 billion, but actual GDP this year is only $900 billion (a recessionary gap). The tax rate is a flat <span class="math inline">\(20\%\)</span>, and government spending is fixed at $200 billion regardless of GDP.</p>
<ol type="1">
<li>Compute actual tax revenue and the actual budget balance.</li>
<li>Compute what tax revenue <em>would be</em> if GDP were at its potential level of $1{,}000 billion.</li>
<li>Compute the cyclically adjusted budget balance.</li>
<li>What does the comparison tell you about the <em>stance</em> of fiscal policy?</li>
</ol>
</div>
</section>
<section id="solution-actual-vs.-cyclically-adjusted-budget" class="slide level2">
<h2>Solution: Actual vs.&nbsp;Cyclically Adjusted Budget</h2>
<div style="font-size: 1.15em;">
<ol type="1">
<li>Actual revenue <span class="math inline">\(= 0.20 \times 900 = 180\)</span>. Actual balance <span class="math inline">\(= 180 - 200 = -20\)</span> (a $20 billion deficit).</li>
</ol>
</div>
<div class="fragment">
<div style="font-size: 1.15em;">
<ol start="2" type="1">
<li>Revenue at potential GDP <span class="math inline">\(= 0.20 \times 1{,}000 = 200\)</span>.</li>
</ol>
</div>
</div>
<div class="fragment">
<div style="font-size: 1.15em;">
<ol start="3" type="1">
<li>Cyclically adjusted balance <span class="math inline">\(= 200 - 200 = 0\)</span> (balanced).</li>
</ol>
</div>
</div>
<div class="fragment">
<div style="font-size: 1.15em;">
<ol start="4" type="1">
<li>The actual $20 billion deficit is entirely a <em>cyclical</em> result of GDP sitting below potential, automatic stabilizers working as intended. The cyclically adjusted budget of <span class="math inline">\(0\)</span> shows that fiscal <em>policy itself</em> is neither expansionary nor contractionary here, it is neutral.</li>
</ol>
</div>
</div>
</section></section>
<section>
<section id="public-debt" class="title-slide slide level1 center">
<h1>Public Debt</h1>

</section>
<section id="what-is-the-public-debt" class="slide level2">
<h2>What Is the Public Debt?</h2>
<div style="font-size: 1.2em;">
<p>The <strong>public debt</strong> is the accumulated total of past budget deficits, minus past surpluses. Each year’s deficit adds to the debt; each year’s surplus subtracts from it.</p>
<ul>
<li>The public debt is a <em>stock</em> (accumulated over time), while the deficit or surplus is a <em>flow</em> (measured within one year).</li>
<li>A country can run a deficit in some years and a surplus in others; the debt reflects the running total.</li>
</ul>
</div>
</section>
<section id="measuring-debt-absolute-dollars-vs.-percent-of-gdp" class="slide level2">
<h2>Measuring Debt: Absolute Dollars vs.&nbsp;Percent of GDP</h2>
<div style="font-size: 1.2em;">
<p>The public debt can be measured two ways:</p>
<ul>
<li><strong>Absolute dollar terms</strong>: the total dollar amount owed. Useful, but hard to compare across time or across countries of very different sizes.</li>
<li><strong>As a percentage of GDP</strong>: the debt relative to the size of the economy that has to service it.</li>
</ul>
<p><em>The percent-of-GDP measure is more meaningful for comparing debt burdens over time or across countries, since a larger economy can support a larger absolute debt without the burden being any heavier.</em></p>
</div>
</section>
<section id="refinancing-vs.-retiring-the-debt" class="slide level2">
<h2>Refinancing vs.&nbsp;Retiring the Debt</h2>
<div style="font-size: 1.2em;">
<p>Governments manage maturing debt in two very different ways:</p>
<ul>
<li><strong>Refinancing</strong> (rolling over): selling new bonds to pay off bonds that are maturing. The debt is <em>not</em> paid off, it is simply carried forward.</li>
<li><strong>Retiring</strong> the debt: actually paying it off, using tax revenue or a budget surplus, so the debt shrinks.</li>
</ul>
<p><em>In practice, most government debt is continuously refinanced rather than retired.</em></p>
</div>
</section>
<section id="internally-held-vs.-externally-held-debt" class="slide level2">
<h2>Internally Held vs.&nbsp;Externally Held Debt</h2>
<div style="font-size: 1.2em;">
<p>Public debt can be held by different lenders:</p>
<ul>
<li><strong>Internally held debt</strong>: owed to a country’s own citizens, banks, and institutions.</li>
<li><strong>Externally held debt</strong>: owed to foreign lenders (governments, institutions, or individuals abroad).</li>
</ul>
<p><em>Internally held debt mostly redistributes purchasing power within the country, repayment goes from domestic taxpayers to domestic bondholders. Externally held debt is different: repayment sends purchasing power abroad, a real burden that internal debt does not carry in the same way.</em></p>
</div>
</section>
<section id="connecting-back-crowding-out-chapter-6" class="slide level2">
<h2>Connecting Back: Crowding Out (Chapter 6)</h2>
<div style="font-size: 1.2em;">
<p>Chapter 6 introduced the <strong>market for loanable funds</strong>, where borrowers and savers meet and the real interest rate is determined.</p>
<ul>
<li>When the government runs a deficit, it must borrow, competing with private borrowers for the same pool of loanable funds.</li>
<li>This added demand for loanable funds can push the real interest rate <em>up</em>.</li>
<li>A higher real interest rate discourages some private investment, this is the <strong>crowding-out effect</strong>.</li>
</ul>
<p><em>Crowding out partially offsets the stimulative effect of expansionary fiscal policy: some of the boost from higher G is undone by lower private investment.</em></p>
</div>
</section>
<section id="example-accumulating-the-public-debt" class="slide level2">
<h2>Example: Accumulating the Public Debt</h2>
<div style="font-size: 1.2em;">
<p>A small country starts with zero public debt. Over four years, its budget results (illustrative, in billions) are:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Year</th>
<th>Deficit (+) or Surplus (-)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Deficit of 50</td>
</tr>
<tr class="even">
<td>2</td>
<td>Deficit of 30</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Surplus of 10</td>
</tr>
<tr class="even">
<td>4</td>
<td>Deficit of 20</td>
</tr>
</tbody>
</table>
<p>This country’s GDP in Year 4 is $900 billion.</p>
<ol type="1">
<li>Compute the accumulated public debt at the end of each year.</li>
<li>Express the Year 4 debt as a percentage of Year 4 GDP.</li>
</ol>
</div>
</section>
<section id="solution-accumulating-the-public-debt" class="slide level2">
<h2>Solution: Accumulating the Public Debt</h2>
<div style="font-size: 1.15em;">
<ol type="1">
<li>End of Year 1: <span class="math inline">\(0 + 50 = 50\)</span>. End of Year 2: <span class="math inline">\(50 + 30 = 80\)</span>. End of Year 3: <span class="math inline">\(80 - 10 = 70\)</span> (a surplus <em>reduces</em> the debt). End of Year 4: <span class="math inline">\(70 + 20 = 90\)</span>.</li>
</ol>
</div>
<div class="fragment">
<div style="font-size: 1.15em;">
<ol start="2" type="1">
<li>Accumulated public debt <span class="math inline">\(= 90\)</span> billion. Debt-to-GDP <span class="math inline">\(= 90 / 900 = 10\%\)</span>.</li>
</ol>
</div>
</div>
<div class="fragment">
<div style="font-size: 1.15em;">
<p><em>A single year’s surplus (Year 3) slowed the growth of the debt, but did not come close to eliminating it. The debt is a running total of every year’s result, not just the most recent one.</em></p>
</div>
</div>
</section>
<section id="real-data-the-public-debt" class="slide level2">
<h2>Real Data: The Public Debt</h2>
<div class="columns">
<div class="column" style="width:60%;">
<!-- FRED EMBED PLACEHOLDER: series GFDEBTN, Federal Debt: Total Public Debt, millions of dollars, quarterly -->
<!-- FRED EMBED PLACEHOLDER: series GFDEGDQ188S, Federal Debt: Total Public Debt as Percent of GDP, quarterly -->
</div><div class="column" style="width:40%;">
<div class="r-stack">
<div class="fragment current-visible">
<ol type="1">
<li>Why might the dollar-amount debt series (GFDEBTN) look like it only ever goes up, even in years the economy grew strongly?</li>
</ol>
</div>
<div class="fragment current-visible">
<p><em>Answer:</em> the federal government has run a deficit, adding to the debt, in nearly every recent year, and most maturing debt is refinanced rather than retired, so the total keeps climbing.</p>
</div>
<div class="fragment current-visible">
<ol start="2" type="1">
<li>Why look at debt as a percent of GDP (GFDEGDQ188S) instead of just the dollar amount?</li>
</ol>
</div>
<div class="fragment current-visible">
<p><em>Answer:</em> percent of GDP accounts for the size of the economy that has to service the debt, making it possible to compare debt burdens meaningfully across different years or countries.</p>
</div>
<div class="fragment current-visible">
<ol start="3" type="1">
<li>Around a recession, would you expect the percent-of-GDP series to rise for reasons beyond new borrowing?</li>
</ol>
</div>
<div class="fragment current-visible">
<p><em>Answer:</em> yes, GDP itself falls in a recession, which mechanically raises the debt-to-GDP ratio even if the dollar amount of new borrowing were unchanged, on top of automatic stabilizers adding to the deficit.</p>
</div>
</div>
</div></div>
</section>
<section id="looking-ahead-monetary-policy-chapters-14-15" class="slide level2">
<h2>Looking Ahead: Monetary Policy (Chapters 14-15)</h2>
<div style="font-size: 1.2em;">
<p>Fiscal policy is only one set of tools for stabilizing the economy. It works through Congress and the President, changing G and T to shift AD, and it is subject to the legislative lags discussed earlier.</p>
<ul>
<li>Chapters 14 and 15 cover <strong>monetary policy</strong>: the Federal Reserve’s parallel set of tools for shifting AD, working through interest rates and the money supply rather than government spending and taxes.</li>
<li>Monetary policy is generally faster to implement than discretionary fiscal policy, since it does not require new legislation.</li>
</ul>
<p><em>Two different levers, the same goal: keeping equilibrium GDP close to potential GDP.</em></p>
</div>
</section>
<section id="wrap-up" class="slide level2">
<h2>Wrap Up</h2>
<div style="font-size: 1.1em;">
<ul>
<li><strong>Discretionary fiscal policy</strong> deliberately changes G and/or T to shift AD: <em>expansionary</em> (raise G, cut T) to close a recessionary gap, <em>contractionary</em> (cut G, raise T) to close an inflationary gap.</li>
<li>A dollar of G moves GDP more than a dollar of T, since <span class="math inline">\(\Delta \text{GDP} = \Delta G \times \text{multiplier}\)</span> versus <span class="math inline">\(\Delta T \times \text{MPC} \times \text{multiplier}\)</span>. The <em>balanced-budget multiplier</em> shows equal increases in G and T still raise GDP, by that same dollar amount.</li>
<li><strong>Automatic stabilizers</strong> (progressive taxes, transfer payments) cushion the business cycle without new legislation; a more progressive tax system stabilizes more.</li>
<li>The <strong>cyclically adjusted budget</strong> strips out the business cycle to reveal the true stance of fiscal policy, separate from the actual deficit or surplus.</li>
<li>The <strong>public debt</strong> accumulates from past deficits and surpluses, is better measured as a percent of GDP, and can be refinanced or retired, held internally or externally. Deficit-financed borrowing can <em>crowd out</em> private investment.</li>
</ul>
</div>
<div style="font-size: 1.1em; padding-top: 0.3em;">
<p><em>Looking ahead:</em> Chapters 14 and 15 cover monetary policy, the Federal Reserve’s own set of tools for managing aggregate demand.</p>
</div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="ch13_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="ch13_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="ch13_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="ch13_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="ch13_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="ch13_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="ch13_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="ch13_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="ch13_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="ch13_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>