project:
  type: website
  output-dir: docs
  pre-render:
    - quarto render ../syllabus/
    - quarto render ../lecture-slides/

  post-render:
    - touch docs/.nojekyll

website:
  page-navigation: false
  open-graph: true
  bread-crumbs: false
  title: ECO 112 - Fall 2026
  description: ECO 112 | Principles of Macroeconomics | Fall 2026
  favicon: assets/favicon.ico
  site-url: https://m-braaksma.github.io/eco112_fall2026/

  page-footer:
    right: >
      <div style='text-align:right;'>
        &copy; Copyright 2026<br>
        This site is built with
        <a href='https://quarto.org/' style='color:#a9a9aa;font-weight:bold;'>Quarto</a>
      </div>
    background: "#660033"

  sidebar:
    background: "#660033"
    logo: "assets/sidebar_logo.png"
    pinned: true
    align: center
    style: "docked"
    collapse-level: 2
    search: true
    tools:
      - icon: mortarboard-fill
        href: https://moodle.augsburg.edu/moodle2021/course/view.php?id=17214
        text: "Moodle"
        target: _blank
      - icon: journal-bookmark-fill
        href: https://connect.edu.mheducation.com/instructor/course/156928764/section/156928765?isLMSRequest=true&isDeployToLms=false
        text: "Connect"
        target: _blank

    contents:
      - section: "Course information"
        contents:
          - href: course-syllabus.qmd
            text: Overview and Syllabus
          - href: index.qmd
            text: Schedule
          - href: course-support.qmd
            text: Support
          - href: course-printing.qmd
            text: Printing

      - section: "Topics"
        contents:
          - section: "Ch 1: Choices"
            contents:
              - href: lecture/ch01.qmd
                text: Slides
              - href: lecture/ch01-links.qmd
                text: Useful Links
              - href: lecture/ch01-practice.qmd
                text: Practice Problems
          - section: "Ch 2: Market System"
            contents:
              - href: lecture/ch02.qmd
                text: Slides
              - href: lecture/ch02-links.qmd
                text: Useful Links
              - href: lecture/ch02-practice.qmd
                text: Practice Problems
          - section: "Ch 3: Supply, Demand, Equilibrium"
            contents:
              - href: lecture/ch03.qmd
                text: Slides
              - href: lecture/ch03-links.qmd
                text: Useful Links
              - href: lecture/ch03-practice.qmd
                text: Practice Problems
          # - section: "Ch 6: Intro to Macroeconomics"
          #   contents:
          #     - href: lecture/ch06.qmd
          #       text: Slides
          #     - href: lecture/ch06-links.qmd
          #       text: Useful Links
          #     - href: lecture/ch06-practice.qmd
          #       text: Practice Problems
          # - section: "Ch 7: National Income"
          #   contents:
          #     - href: lecture/ch07.qmd
          #       text: Slides
          #     - href: lecture/ch07-links.qmd
          #       text: Useful Links
          #     - href: lecture/ch07-practice.qmd
          #       text: Practice Problems
          # - section: "Ch 8: Economic Growth"
          #   contents:
          #     - href: lecture/ch08.qmd
          #       text: Slides
          #     - href: lecture/ch08-links.qmd
          #       text: Useful Links
          #     - href: lecture/ch08-practice.qmd
          #       text: Practice Problems
          # - section: "Ch 9: Business Cycles, Unemployment, Inflation"
          #   contents:
          #     - href: lecture/ch09.qmd
          #       text: Slides
          #     - href: lecture/ch09-links.qmd
          #       text: Useful Links
          #     - href: lecture/ch09-practice.qmd
          #       text: Practice Problems
          # - section: "Ch 10: Basic Macroeconomic Relationships"
          #   contents:
          #     - href: lecture/ch10.qmd
          #       text: Slides
          #     - href: lecture/ch10-links.qmd
          #       text: Useful Links
          #     - href: lecture/ch10-practice.qmd
          #       text: Practice Problems
          # - section: "Ch 11: Aggregate Expenditure Model"
          #   contents:
          #     - href: lecture/ch11.qmd
          #       text: Slides
          #     - href: lecture/ch11-links.qmd
          #       text: Useful Links
          #     - href: lecture/ch11-practice.qmd
          #       text: Practice Problems
          # - section: "Ch 12: Aggregate Demand & Supply"
          #   contents:
          #     - href: lecture/ch12.qmd
          #       text: Slides
          #     - href: lecture/ch12-links.qmd
          #       text: Useful Links
          #     - href: lecture/ch12-practice.qmd
          #       text: Practice Problems
          # - section: "Ch 13: Fiscal Policy"
          #   contents:
          #     - href: lecture/ch13.qmd
          #       text: Slides
          #     - href: lecture/ch13-links.qmd
          #       text: Useful Links
          #     - href: lecture/ch13-practice.qmd
          #       text: Practice Problems
          # - section: "Ch 14: Money and Banking"
          #   contents:
          #     - href: lecture/ch14.qmd
          #       text: Slides
          #     - href: lecture/ch14-links.qmd
          #       text: Useful Links
          #     - href: lecture/ch14-practice.qmd
          #       text: Practice Problems
          # - section: "Ch 15: Monetary Policy"
          #   contents:
          #     - href: lecture/ch15.qmd
          #       text: Slides
          #     - href: lecture/ch15-links.qmd
          #       text: Useful Links
          #     - href: lecture/ch15-practice.qmd
          #       text: Practice Problems
          # - section: "Ch 16: Financial Economics"
          #   contents:
          #     - href: lecture/ch16.qmd
          #       text: Slides
          #     - href: lecture/ch16-links.qmd
          #       text: Useful Links
          #     - href: lecture/ch16-practice.qmd
          #       text: Practice Problems
          # - section: "Ch 17: Extending Aggregate Supply"
          #   contents:
          #     - href: lecture/ch17.qmd
          #       text: Slides
          #     - href: lecture/ch17-links.qmd
          #       text: Useful Links
          #     - href: lecture/ch17-practice.qmd
          #       text: Practice Problems
          # - section: "Capstone: Macro and the Environment"
          #   contents:
          #     - href: lecture/capstone.qmd
          #       text: Slides
          #     - href: lecture/capstone-links.qmd
          #       text: Useful Links
          #     - href: lecture/capstone-practice.qmd
          #       text: Practice Problems

format:
  html:
    theme: [sandstone, theme.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
